name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node: [4, 6, 8, 10]

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose up
