name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Building the Docker Image with Docker-compose file
      run: docker-compose up
