name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Building Docker Image
      run: docker-compose up
      shell: cmd
        
